require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - bin/**/*
    - config/**/*
    - vendor/**/*
    - db/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120